name: Build, Release, and Docker

on:
  push:
    tags:
      - 'v*'

jobs:
  build-jar:
    name: Build JAR
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3.14.1
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build JAR with Gradle
        run: ./gradlew clean build -x test --info --stacktrace

      - name: Debug Build Output
        run: ls -R app/build/libs/

      - name: List JAR files with details
        run: |
          echo "Contenido detallado de app/build/libs/:"
          ls -l app/build/libs/
          echo "Archivos JAR encontrados:"
          find app/build/libs/ -name '*.jar' -exec ls -l {} \;
