name: Build, Release, and Docker

on:
  push:
    tags:
      - 'v*'

jobs:
  build-jar:
    name: Build JAR
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3.14.1
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build JAR with Gradle
        run: ./gradlew clean build -x test --info --stacktrace

      - name: Debug Build Output
        run: |
          echo "Contenido recursivo de app/build/libs/:"
          ls -R app/build/libs/ || echo "No se encontró app/build/libs/"

      - name: List JAR files with details
        run: |
          echo "Contenido detallado de app/build/libs/:"
          ls -l app/build/libs/ || echo "No se encontró la carpeta app/build/libs/"
          echo "Archivos JAR encontrados:"
          find app/build/libs/ -name '*.jar' -exec ls -l {} \; || echo "No se encontraron archivos .jar"

  build-native:
    name: Build Native Binaries
    needs: build-jar
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-24.04
            output_name: arc-linux-x64
            native_opts: "--static --no-fallback"
          - os: macos-13
            arch: x64
            output_name: arc-macos-x64
            native_opts: "--no-fallback"
          - os: macos-14
            arch: arm64
            output_name: arc-macos-arm64
            native_opts: "--no-fallback"
    steps:
      - uses: actions/checkout@v3

      - name: Download JAR
        uses: actions/download-artifact@v3.0.2
        with:
          name: app-jar
          path: app/build/libs/

      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: '17'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Native Image
        run: |
          native-image -jar app/build/libs/app.jar -H:Name=${{ matrix.output_name }} ${{ matrix.native_opts }}

      - name: Strip Binary
        run: |
          strip ${{ matrix.output_name }} || true

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.output_name }}
          path: ${{ matrix.output_name }}
          if-no-files-found: error

  release:
    needs: build-native
    runs-on: ubuntu-24.04
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3.0.2
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/arc-linux-x64/arc-linux-x64
            artifacts/arc-macos-x64/arc-macos-x64
            artifacts/arc-macos-arm64/arc-macos-arm64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker:
    needs: build-jar
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download JAR
        uses: actions/download-artifact@v3.0.2
        with:
          name: app-jar
          path: app/build/libs/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract repository name to lowercase
        id: repo-name
        run: |
          echo "REPO_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ steps.repo-name.outputs.REPO_NAME }}-cli:${{ github.ref_name }}
            ghcr.io/${{ steps.repo-name.outputs.REPO_NAME }}-cli:latest